import { NextResponse } from 'next/server';

const GA_AIRPORTS = {"0N4":{"code":"0N4","name":"Chandelle Airport","city":"Dover","state":"DE"},"28DE":{"code":"28DE","name":"Albanna Aviation Airport","city":"Felton","state":"DE"},"15N":{"code":"15N","name":"Jenkins Airport","city":"Wyoming","state":"DE"},"1DE5":{"code":"1DE5","name":"Mckeown Airport","city":"Middletown","state":"DE"},"23DE":{"code":"23DE","name":"Full Throttle Farm Airport","city":"Clayton","state":"DE"},"2DE2":{"code":"2DE2","name":"Willaview Airport","city":"Farmington","state":"DE"},"2DE3":{"code":"2DE3","name":"Hrupsa Airport","city":"Felton","state":"DE"},"2DE8":{"code":"2DE8","name":"Murphy's Landing Airport","city":"Milford","state":"DE"},"38N":{"code":"38N","name":"Smyrna Airport","city":"Smyrna","state":"DE"},"DE00":{"code":"DE00","name":"Doyle's Airport","city":"Felton","state":"DE"},"DE04":{"code":"DE04","name":"Newberg Airport","city":"Smyrna","state":"DE"},"DE09":{"code":"DE09","name":"Johnsons Airport","city":"Magnolia","state":"DE"},"DE10":{"code":"DE10","name":"Kimbowrosa Farm Airport","city":"Milford","state":"DE"},"DE11":{"code":"DE11","name":"Drummond Airport","city":"Milford","state":"DE"},"DE14":{"code":"DE14","name":"Huey Airport","city":"Bridgeville","state":"DE"},"DE15":{"code":"DE15","name":"Pevey Airport","city":"Seaford","state":"DE"},"DE17":{"code":"DE17","name":"Sugar Hill Airport","city":"Greenwood","state":"DE"},"DE19":{"code":"DE19","name":"Duffy's Airport","city":"Townsend","state":"DE"},"DE20":{"code":"DE20","name":"Spirit Airpark","city":"Townsend","state":"DE"},"DE21":{"code":"DE21","name":"West Private Airport","city":"Frankford","state":"DE"},"DE23":{"code":"DE23","name":"Ockel Farms Airport","city":"Milton","state":"DE"},"DE25":{"code":"DE25","name":"Eagle Crest-Hudson Airport","city":"Milton","state":"DE"},"DE29":{"code":"DE29","name":"Scotty's Place Airport","city":"Smyrna","state":"DE"},"DE32":{"code":"DE32","name":"Belfair Airport","city":"Felton","state":"DE"},"DE34":{"code":"DE34","name":"Townsend A Airport","city":"Townsend","state":"DE"},"33N":{"code":"33N","name":"Delaware Airpark","city":"Dover/Cheswold","state":"DE"},"D74":{"code":"D74","name":"Chorman Airport","city":"Farmington","state":"DE"},"EVY":{"code":"EVY","name":"Summit Airport","city":"Middletown","state":"DE"},"GED":{"code":"GED","name":"Delaware Coastal Airport","city":"Georgetown","state":"DE"},"N06":{"code":"N06","name":"Laurel Airport","city":"Laurel","state":"DE"}};

export async function GET(request) {
  const { searchParams } = new URL(request.url);
  const code = searchParams.get('code');
  if (!code) return NextResponse.json({ error: 'No code provided' }, { status: 400 });
  const airport = GA_AIRPORTS[code.toUpperCase()];
  if (!airport) return NextResponse.json({ error: 'Airport not found' }, { status: 404 });
  return NextResponse.json(airport);
}
